[package]
name = "pega-core"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version = "0.18.0", features = ["cuda-12040"] }
tracing = "0.1"
offset-allocator = "0.2.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "pinned_copy"
harness = false
