[package]
name = "pegaflow-transfer"
version.workspace = true
edition.workspace = true

[dependencies]
parking_lot.workspace = true
sideway.workspace = true
thiserror = "2.0"

[dev-dependencies]
cudarc.workspace = true
