[package]
name = "pegaflow-py"
version = "0.0.1"
edition.workspace = true

[lib]
name = "pegaflow"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
pega-core.workspace = true
tracing-subscriber.workspace = true
